name: flutter_application_2
description: A new Flutter project.

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.0.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.0.1
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.1.0
  provider: ^6.1.2
  firebase_storage: ^12.2.0
  image_picker: ^0.8.7+3 
  http:
  googleapis:
  googleapis_auth:
  geolocator: ^12.0.0  
  intl: ^0.18.0
  permission_handler: ^11.2.0
  geocoding: ^3.0.0
  firebase_app_check:
  path_provider: ^2.0.11
  connectivity_plus: ^6.0.5
  # url_launcher: ^6.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 
  flutter_launcher_icons: ^0.13.1 

flutter:
  uses-material-design: true
  assets:
    - assets/service-key.json
    - assets/noInternet.jpg
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"